Bump serde_yaml to 0.8 to fix panic.
Fixes:
```
thread 'main' panicked at 'attempted to leave type
    `linked_hash_map::Node<value::Value, value::Value>`
    uninitialized, which is invalid',
stack backtrace:
  11: serde_yaml::de::from_str
             at serde_yaml-0.7.5/src/de.rs:729
  12: rsp2_tasks_config::monomorphize::value_from_str
             at rsp2/src/tasks/config/lib.rs:107
  13: rsp2_tasks_config::monomorphize::YamlRead::from_dyn_reader
             at rsp2/src/tasks/config/lib.rs:64
  14: rsp2_tasks_config::monomorphize::YamlRead::from_reader
             at rsp2/src/tasks/config/lib.rs:48
  15: rsp2_tasks::ui::cfg_merging::Config::_read_file
             at rsp2/src/tasks/ui/cfg_merging.rs:81
```